on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  PYTHON_VERSION: '3.10'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python version
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies into .python_packages
        run: |
          pip install --target=.python_packages -r requirements.txt

      - name: Zip artifact for deployment
        run: |
          zip -r release.zip . -x "venv/*" ".git/*" ".vscode/*" "__pycache__/*" "*.pyc"

      - name: 'Deploy to Azure Functions'
        uses: Azure/functions-action@v1
        with:
          app-name: 'func71'
          slot-name: 'Production'
          package: release.zip
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_EDF961D9D91045A684BA7D91E47AFD5D }}
          sku: 'flexconsumption'
